<a href="https://colab.research.google.com/github/bhanu0925/NLP/blob/main/Transformers_tokenizer_pipelines.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
from google.colab import drive
drive.mount('/content/drive')
import os
ROOT = "/content/drive/MyDrive/NLP/Transformer"
os.chdir(ROOT)
try:
  from transformers import pipeline
except Exception as e:
  print(e)
print("installing .......")
!pip install datasets transformers[sentencepiece] -q
from transformers import pipeline

No module named 'transformers'
installing .......
     |████████████████████████████████| 346 kB 10.1 MB/s 
     |████████████████████████████████| 4.2 MB 12.1 MB/s 
     |████████████████████████████████| 1.1 MB 61.0 MB/s 
     |████████████████████████████████| 86 kB 6.9 MB/s 
     |████████████████████████████████| 86 kB 5.5 MB/s 
     |████████████████████████████████| 140 kB 65.0 MB/s 
     |████████████████████████████████| 212 kB 72.2 MB/s 
     |████████████████████████████████| 596 kB 53.7 MB/s 
     |████████████████████████████████| 127 kB 61.5 MB/s 
     |████████████████████████████████| 94 kB 3.4 MB/s 
     |████████████████████████████████| 271 kB 66.6 MB/s 
     |████████████████████████████████| 144 kB 21.7 MB/s 
     |████████████████████████████████| 112 kB 73.6 MB/s 
     |████████████████████████████████| 6.6 MB 50.8 MB/s 
     |████████████████████████████████| 1.2 MB 34.9 MB/s 
ERROR: pip's dependency resolver does not currently take into account all the packages

In [4]:
import torch
torch.cuda.is_available()

True

In [5]:
classifier = pipeline("sentiment-analysis")

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english)


Downloading:   0%|          | 0.00/629 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/255M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

In [6]:
classifier("I love my india")

[{'label': 'POSITIVE', 'score': 0.9998658895492554}]

In [10]:
%time
classifier("I love my india")

CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 8.11 µs


[{'label': 'POSITIVE', 'score': 0.9998658895492554}]

## what happens behind the seen when we use pipeline

In [12]:
# 1 Tokenizer

In [13]:
from transformers import AutoTokenizer

In [17]:
ckpt = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(ckpt)

In [19]:
input = "i love india"
tokenizer(input)

{'input_ids': [101, 1045, 2293, 2634, 102], 'attention_mask': [1, 1, 1, 1, 1]}

In [22]:
batch_input = ['i am bhanu','i am bhanu working at home']
tokenizer(batch_input,padding=True)

{'input_ids': [[101, 1045, 2572, 1038, 4819, 2226, 102, 0, 0, 0], [101, 1045, 2572, 1038, 4819, 2226, 2551, 2012, 2188, 102]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 0, 0, 0], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}

In [25]:
out_pytorch_tensors = tokenizer(batch_input,padding=True,return_tensors='pt')
out_pytorch_tensors

{'input_ids': tensor([[ 101, 1045, 2572, 1038, 4819, 2226,  102,    0,    0,    0],
        [ 101, 1045, 2572, 1038, 4819, 2226, 2551, 2012, 2188,  102]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [28]:
from transformers import AutoModel  # get the pretrained models

In [29]:
model_ckpt = AutoModel.from_pretrained(ckpt)

Some weights of the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing DistilBertModel: ['classifier.bias', 'classifier.weight', 'pre_classifier.weight', 'pre_classifier.bias']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [31]:
model_ckpt  # pretrained weights

DistilBertModel(
  (embeddings): Embeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (transformer): Transformer(
    (layer): ModuleList(
      (0): TransformerBlock(
        (attention): MultiHeadSelfAttention(
          (dropout): Dropout(p=0.1, inplace=False)
          (q_lin): Linear(in_features=768, out_features=768, bias=True)
          (k_lin): Linear(in_features=768, out_features=768, bias=True)
          (v_lin): Linear(in_features=768, out_features=768, bias=True)
          (out_lin): Linear(in_features=768, out_features=768, bias=True)
        )
        (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        (ffn): FFN(
          (dropout): Dropout(p=0.1, inplace=False)
          (lin1): Linear(in_features=768, out_features=3072, bias=True)
          (lin2): Linear(i

In [32]:
out_tf_tensors = tokenizer(batch_input,padding=True,return_tensors='tf')  # get the tensors
out_tf_tensors

{'input_ids': <tf.Tensor: shape=(2, 10), dtype=int32, numpy=
array([[ 101, 1045, 2572, 1038, 4819, 2226,  102,    0,    0,    0],
       [ 101, 1045, 2572, 1038, 4819, 2226, 2551, 2012, 2188,  102]],
      dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 10), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [33]:
logits = model_ckpt(**out_pytorch_tensors)
logits

BaseModelOutput([('last_hidden_state',
                  tensor([[[ 0.2620,  0.1608,  0.2944,  ...,  0.5867,  0.6161,  0.0737],
                           [ 0.8496,  0.2086,  0.1957,  ...,  0.5984,  0.6468, -0.0623],
                           [ 0.6311,  0.4488,  0.4759,  ...,  0.3629,  0.5008,  0.1158],
                           ...,
                           [ 0.4135, -0.1267,  0.3289,  ...,  0.9748,  0.5974,  0.0526],
                           [ 0.3116, -0.0510,  0.2717,  ...,  1.0328,  0.6127,  0.0494],
                           [ 0.2265, -0.0184,  0.2905,  ...,  1.0341,  0.6900,  0.0781]],
                  
                          [[ 0.4485,  0.1651,  0.2880,  ...,  0.2834,  0.5397,  0.0886],
                           [ 0.8471,  0.3991, -0.0045,  ...,  0.1122,  0.6634, -0.0866],
                           [ 0.3593,  0.5699,  0.5582,  ...,  0.2672,  0.6704, -0.0191],
                           ...,
                           [ 0.6676,  0.4001,  0.0725,  ...,  0.0156,  0.220

In [37]:
logits['last_hidden_state'].shape

torch.Size([2, 10, 768])

In [38]:
batch_size,sequence_len,Hidden_state = logits['last_hidden_state'].shape
batch_size,sequence_len,Hidden_state

(2, 10, 768)

In [40]:
from transformers import AutoModelForSequenceClassification
model_2 = AutoModelForSequenceClassification.from_pretrained(ckpt)
pred = model_2(**out_pytorch_tensors)
pred

SequenceClassifierOutput([('logits', tensor([[-2.8457,  3.0905],
                                   [-1.9292,  2.0735]], grad_fn=<AddmmBackward0>))])

In [42]:
import torch
pred_prob = torch.nn.functional.softmax(pred.logits, dim=1)
pred_prob

tensor([[0.0026, 0.9974],
        [0.0179, 0.9821]], grad_fn=<SoftmaxBackward0>)

In [43]:
model_2.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}

In [44]:
torch.argmax(pred_prob, dim=-1)

tensor([1, 1])